config/routes.rb
Rails.application.routes.draw do
  devise_for :organizers
  devise_for :riders
  devise_for :sponsors, :controllers => { :omniauth_callbacks => "callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get "ride_requests", to: "sponsors#ride_requests", as: :ride_requests

  match "request_ride", to: "riders#request_ride", as: :request_ride, via: [:get, :post]
  get "sponsor_ride", to: "requests#sponsor_ride", as: :sponsor_ride
  post "create_ride_request", to: "riders#create_ride_request", as: :create_ride_request

  resources :riders
  resources :organizers
	resources :sponsors

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/views/home/_add_rider_modal.html.erb
<div id="add-rider-modal" uk-modal>
  <div class="uk-modal-dialog">
    <div class="uk-modal-header">
      <h2 class="uk-modal-title">Add a Rider</h2>
    </div>
    <div class="uk-modal-body uk-padding-remove-bottom uk-padding-remove-top">
      <%= form_for Rider.new, url: { action: "create", controller: "riders" }, class: "uk-form-stacked" do |f| %>
        <div class="uk-margin">
          <%= label_tag "Phone Number", nil, class: "uk-form-label" %>
          <div class="uk-form-controls">
            <%= f.text_field :phone_number, class: "uk-input" %>
          </div>
        </div>
        
        <div class="uk-margin">
          <%= label_tag "First Name", nil, class: "uk-form-label" %>
          <div class="uk-form-controls">
            <%= f.text_field :first_name, class: "uk-input" %>
          </div>
        </div>

        <div class="uk-margin">
          <%= label_tag "Last Name", nil, class: "uk-form-label" %>
          <div class="uk-form-controls">
            <%= f.text_field :last_name, class: "uk-input" %>
          </div>
        </div>

        <div class="uk-align-right">
          <%= f.submit "Add", class: "uk-button blue-button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_sign_up_modal.html.erb
<div id="sign-up-modal" uk-modal>
  <div class="uk-modal-dialog">
    <div class="uk-modal-header">
      <h2 class="uk-modal-title">Sign Up</h2>
    </div>
    <div class="uk-modal-body uk-padding-remove-bottom">
      <%= form_tag organizer_registration_path, method: :post do %>
        <div class="uk-margin">
          <%= text_field_tag "organizer[email]", :email, placeholder: "Email", class: "uk-input", "v-model": "newUser.email" %>
        </div>

        <div class="uk-margin">
          <%= password_field_tag "organizer[password]", :password, placeholder: "Password", class: "uk-input", "v-model": "newUser.password" %>
        </div>

        <div class="uk-margin">
          <%= password_field_tag "organizer[password_confirmation]", :password_confirmation, placeholder: "Confirm Password", class: "uk-input", "v-model": "newUser.passwordConfirm" %>
          <small class="text-color-red" v-show="showPasswordsDoNotMatch">Passwords do not match</small>
        </div>

        <div class="uk-align-right">
          <%= submit_tag "Sign Up", class: "uk-button blue-button", ":disabled": "disableSignUpButton" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="uk-position-center">
  <div class="uk-margin-left">
    <div class="uk-child-width-1-2 uk-grid-large" uk-grid>
      <div>
        <div id="vue-app-home-page" v-cloak>
          <%= render partial: "home/sign_up_modal" %>
          <%= render partial: "home/add_rider_modal" %>
          <h1 class="text-color-blue uk-text-bold">I am {{ selectedUserType === "organizer" ? "an" : "a" }} {{ _.capitalize(selectedUserType) }} </h1>
          <div class="uk-form-controls">
              <label><input class="uk-radio" type="radio" name="user-type-radio" v-model="selectedUserType" value="rider"> Rider</label>
              <label><input class="uk-radio uk-margin-left" type="radio" name="user-type-radio" v-model="selectedUserType" value="sponsor"> Sponsor</label>
              <label><input class="uk-radio uk-margin-left" type="radio" name="user-type-radio" v-model="selectedUserType" value="organizer"> Organizer</label>
          </div>
          <div class="uk-margin-top">
            <div v-if="selectedUserType == 'rider'">
              <%= form_tag request_ride_path, method: :post do %>
                <div class="uk-margin">
                  <div class="uk-form-controls">
                    <%= text_field_tag :phone_number, nil, class: "uk-input", placeholder: "Enter your Phone Number" %>
                  </div>
                </div>
                
                <div class="uk-margin">
                  <div class="uk-form-controls">
                    <%= submit_tag "Request a Ride", class: "uk-button large-button" %>
                  </div>
                </div>
              <% end %>
            </div>

            <div v-if="selectedUserType == 'sponsor'">
              <div class="uk-form-controls">
                <%= link_to "#{ image_tag("Lyft_Logo_White.svg", size: "64x32") } Sign in with Lyft".html_safe, omniauth_authorize_path('sponsor', 'lyft'), class: "uk-button large-button" %>
              </div>
            </div>

            <div v-if="selectedUserType == 'organizer'">
              <% if current_organizer %>
                <div class="uk-form-controls uk-margin">
                  <%= link_to "Add a Rider", "", class: "uk-button large-button", "uk-toggle": "target: #add-rider-modal" %>
                </div>

                <div class="uk-form-controls uk-margin">
                  <%= link_to "View all Riders", riders_path, class: "uk-button large-button" %>
                </div>

                <div class="uk-form-controls uk-margin">
                  <%= link_to "Log Out", destroy_organizer_session_path, method: :delete, class: "uk-button large-button" %>
                </div>
              <% else %>
                <%= form_tag(organizer_session_path) do %>
                  <div class="uk-margin">
                    <div class="uk-form-controls">
                      <%= text_field_tag "organizer[email]", nil, class: "uk-input", placeholder: "Enter your Email" %>
                    </div>
                  </div>

                  <div class="uk-margin">
                    <div class="uk-form-controls">
                      <%= password_field_tag "organizer[password]", nil, class: "uk-input", placeholder: "Enter your Password" %>
                    </div>
                  </div>
                  <div class="uk-margin">
                    <div class="uk-form-controls">
                      <%= submit_tag "Sign In", class: "uk-button large-button" %>
                      <small class="uk-margin-left"><%= link_to "No Account? Sign Up Here", "", "uk-toggle": "target: #sign-up-modal" %></small>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div>
        <%= image_tag image_path("Car_v3_trimmed.png") %>
      </div>
    </div>
  </div>
</div>