config/routes.rb
Rails.application.routes.draw do
  devise_for :organizers
  devise_for :riders
  devise_for :sponsors, :controllers => { :omniauth_callbacks => "callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get "ride_requests", to: "sponsors#ride_requests", as: :ride_requests

  match "request_ride", to: "riders#request_ride", as: :request_ride, via: [:get, :post]
  get "sponsor_ride", to: "requests#sponsor_ride", as: :sponsor_ride
  post "create_ride_request", to: "riders#create_ride_request", as: :create_ride_request

  resources :riders
  resources :organizers
	resources :sponsors

end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:lyft]

  def self.from_omniauth(auth)
    token = auth.credentials['token']
		api = LyftApi.new(token)
		profile = api.get_user_profile.parsed_response
    user = Sponsor.where(provider: auth.provider, email: profile['email']).first_or_create
    user.provider = auth.provider
    user.first_name = profile['first_name']
    user.last_name = profile['last_name']
    user.lyft_access_token = auth.credentials['token']
    user.password = Devise.friendly_token[0,20]
    user.save!
    user
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController

	def show
		@sponsor = Sponsor.where(lyft_access_token: params[:id]).first
	end

  # This can definitely be improved. Look at again tomorrow, seems to work for now
  # Also, when we have Concierge access, see if we can add the estimated_cost
  # to the ride request when it's created. Currently we need a sponsor to hit the ride_estimate
  # endpoint.
	def ride_requests
		lyft = LyftApi.new(current_sponsor.lyft_access_token)
		@ride_requests = RideRequest.all
		@ride_requests.each do |rr|
			ride_coord = RideCoord.where(ride_request_id: rr.id).first
			response = lyft.get_ride_estimate(ride_coord.start_lat, ride_coord.start_long, ride_coord.destination_lat, ride_coord.destination_long)
			response.parsed_response['cost_estimates'].each do |ce|
				if ce['ride_type'] == 'lyft'
					rr.estimated_cost = (ce["estimated_cost_cents_min"] + ce["estimated_cost_cents_max"]) / 2 / 100
					rr.save
				end
			end
		end
	end

end

app/views/sponsors/ride_requests.html.erb
<% @title = "Ride Requests | Sponsor My Lyft" %>
<div class="uk-margin-large-top">
  <div class="uk-position-top-right uk-width-1-5 uk-position-large uk-margin-large-top">
    <%= image_tag "lyft_black_car.png", class:"uk-margin-top" %>
  </div>
  <h3 class="text-color-blue uk-margin-remove-top">Thank you <%= current_sponsor.first_name %> for helping your community</h3>
  <h3 class="uk-text-bold text-color-blue">Requested rides</h3>
  <table class="uk-table">
    <thead>
      <tr>
        <th>
          Name
        </th>
        <th>
          Start Time
        </th>
        <th>
          Starting Location
        </th>
        <th>
          Destination
        </th>
        <th>
          Estimated Cost
        </th>
        <th>
          Status
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @ride_requests.each_with_index do |request, index| %>
        <tr>
          <td><%= "#{request.rider.first_name} #{request.rider.last_name}" %></td>
          <td><%= request.start_time.strftime("%l:%M %p %m %b") if !request.start_time.nil? %></td>
          <td><%= request.start_loc_name %></td>
          <td><%= request.dest_loc_name %></td>
          <td>$ <%= request.estimated_cost %></td>
          <td><%= request.status.titleize %></td>
          <td>
            <% if request.status != 'sponsored' %>
              <%= link_to "Sponsor Ride", sponsor_ride_path(request_id: request.id), class: "uk-button blue-button" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>